=== bible-technology/scripture-burrito/schema/default_metadata.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "https://burrito.bible/schema/default_metadata.schema.json",
    "title": "Scripture Burrito Metadata (Default)",
    "type": "object",
    "description": "Scripture Burrito default variant root.",
    "properties": {
        "meta": {
            "$ref": "default_meta.schema.json"
        },
        "idServers": {
            "$ref": "idservers.schema.json"
        },
        "identification": {
            "$ref": "identification.schema.json"
        },
        "confidentiality": {
            "$ref": "confidentiality.schema.json"
        },
        "type": {
            "$ref": "type.schema.json"
        },
        "relationships": {
            "$ref": "relationships.schema.json"
        },
        "languages": {
            "$ref": "languages.schema.json"
        },
        "countries": {
            "$ref": "countries.schema.json"
        },
        "agencies": {
            "$ref": "agencies.schema.json"
        },
        "copyright": {
            "$ref": "copyright.schema.json"
        },
        "ingredients": {
            "$ref": "ingredients.schema.json"
        },
        "names": {
            "$ref": "names.schema.json"
        },
        "recipeSpecs": {
            "$ref": "recipe_specs.schema.json"
        },
        "progress": {
            "$ref": "progress.schema.json"
        }
    },
    "required": [
        "meta",
        "idServers",
        "identification",
        "confidentiality",
        "type"
    ],
    "additionalProperties": false,
    "if": {
        "properties": {
            "type": {
                "properties": {
                    "flavorType": {
                        "enum": [
                            "scripture",
                            "gloss"
                        ]
                    }
                }
            }
        }
    },
    "then": {
        "required": [
            "languages",
            "names"
        ]
    }
}

=== bible-technology/scripture-burrito/docs/examples/artifacts/textTranslation_derived.json
{
    "meta": {
        "version": "0.2.0",
        "variant": "derived_foo",
        "dateCreated": "2019-02-19T01:02:03+01:00",
        "generator": {
            "softwareName": "Burrito Factory",
            "softwareVersion": "0.1",
            "userName": "Jane Doe"
        },
        "uploader": {
            "softwareName": "Burrito Truck",
            "softwareVersion": "0.1",
            "userId": "dbl::5678",
            "userName": "Josh Buck"
        },
        "defaultLanguage": "en",
        "comments": [
            "Experimenting with i18n",
            "Fixed canon before upload. ~Josh"
        ]
    },
    "idServers": {
        "dbl": {
            "id": "https://thedigitalbiblelibrary.org",
            "name": {
                "en": "The Digital Bible Library"
            }
        },
        "agmt": {
            "id": "http://registry.autographamt.com",
            "name": {
                "en": "Autographa"
            }
        },
        "x-atl": {
            "id": "http://atlantisbibleconsortium.net"
        }
    },
    "identification": {
        "systemId": {
            "dbl": {
                "id": "0123456789abcdef",
                "revision": "23"
            },
            "gbc": {
                "id": "55df02965117ad3f2201309b"
            },
            "paratext": {
                "id": "2d5220a02a7aaac6bcc2831ae262e9aaca5e1abd"
            }
        },
        "idServer": "dbl",
        "name": {
            "en": "Scripture Burrito Demo Text Bible",
            "fr": "Cr\u00eape mexicaine biblique surdimensionn\u00e9e (d\u00e9monstration)"
        },
        "description": {
            "en": "A Demonstration Scripture Burrito containing Text, like Paratext Might One Day Produce"
        },
        "abbreviation": {
            "en": "DSB",
            "fr": "CMBS"
        }
    },
    "confidentiality": {
        "metadata": "unrestricted",
        "source": "private",
        "publications": "restricted"
    },
    "type": {
        "flavorType": {
            "name": "scripture",
            "currentScope": {
                "GEN": [],
                "EXO": [
                    "1",
                    "3-12",
                    "13:4",
                    "14:3-8",
                    "15:8-16:2"
                ],
                "LEV": [
                    "2-3"
                ],
                "MAT": [
                    "1",
                    "5",
                    "7-11"
                ]
            },
            "canonType": [
                "ot",
                "nt"
            ],
            "canonSpec": {
                "ot": {
                    "name": "western"
                },
                "nt": {
                    "name": "x-matthewOnlyMillenialists",
                    "books": [
                        "MAT"
                    ]
                }
            },
            "flavor": {
                "name": "textTranslation",
                "projectType": "standard",
                "audience": "common",
                "translationType": "newTranslation",
                "usfmVersion": "3.1.rc49"
            }
        }
    },
    "relationships": [
        {
            "relationType": "expression",
            "flavor": "scripturePrint",
            "id": "dbl::fedcba9876543210:2"
        },
        {
            "relationType": "expression",
            "flavor": "glossedTextStory",
            "id": "x-atl::gl47"
        },
        {
            "relationType": "parascriptural",
            "flavor": "parascripturalWordAlignment",
            "id": "agmt::irvmal-4-wh"
        }
    ],
    "languages": [
        {
            "tag": "en",
            "name": {
                "en": "English",
                "de": "Englisch",
                "fr": "anglais"
            },
            "numberingSystem": "latn"
        }
    ],
    "countries": [
        {
            "code": "NL",
            "name": {
                "nl": "Nederland",
                "kl": "Pukkitsormiut",
                "la": "Batavia",
                "ru": "\u041d\u0438\u0434\u0435\u0440\u043b\u0430\u043d\u0434\u044b"
            }
        }
    ],
    "agencies": [
        {
            "id": "dbl::23",
            "name": {
                "en": "Burritos R Us Inc"
            },
            "abbr": {
                "en": "BRU"
            },
            "url": "https://burritos-r-us.org",
            "roles": [
                "rightsHolder",
                "content",
                "finance",
                "management",
                "publication",
                "qa"
            ]
        },
        {
            "id": "dbl::29",
            "name": {
                "en": "We Manage Burritos"
            },
            "roles": [
                "qa"
            ]
        }
    ],
    "copyright": {
        "rightsHolderAgencies": [
            0,
            1
        ],
        "rightsAdminAgency": 1,
        "licenses": [
            {
                "url": "https://burritos-r-us.org/licenses/3247"
            }
        ],
        "shortStatementPlain": {
            "fr": "\u00a9 Burritos R Us 2019."
        },
        "fullStatementPlain": {
            "fr": "\u00a9 Burritos R Us 2019. Tous droits r\u00e9serv\u00e9s."
        },
        "fullStatementRich": {
            "fr": "<p><b>\u00a9 Burritos R Us 2019.</b></p><p><i>Tous droits r\u00e9serv\u00e9s.</i></p>"
        }
    },
    "ingredients": {
        "source/usfm/OTINT.sfm": {
            "checksum": {
                "md5": "0123456789abcdef0123456789abcdef"
            },
            "mimeType": "text/x-sfm",
            "role": "intot",
            "size": 1234,
            "isSource": true
        },
        "source/usfm/GEN.sfm": {
            "checksum": {
                "md5": "0123456789abcdef0123456789abcdef"
            },
            "mimeType": "text/x-sfm",
            "scope": {
                "GEN": []
            },
            "size": 1234,
            "isSource": true
        },
        "source/usfm/EXO.sfm": {
            "checksum": {
                "md5": "0123456789abcdef0123456789abcdef"
            },
            "mimeType": "text/x-sfm",
            "scope": {
                "EXO": [
                    "1-12"
                ]
            },
            "size": 1234,
            "isSource": true
        },
        "source/usfm/LEV.sfm": {
            "checksum": {
                "md5": "0123456789abcdef0123456789abcdef"
            },
            "mimeType": "text/x-sfm",
            "scope": {
                "LEV": [
                    "2:3-3:7"
                ]
            },
            "size": 1234,
            "isSource": true
        },
        "source/usfm/INTNT.sfm": {
            "checksum": {
                "md5": "0123456789abcdef0123456789abcdef"
            },
            "mimeType": "text/x-sfm",
            "role": "intnt",
            "size": 1234,
            "isSource": true
        },
        "source/usfm/INTMAT.sfm": {
            "checksum": {
                "md5": "0123456789abcdef0123456789abcdef"
            },
            "mimeType": "text/x-sfm",
            "role": "intMAT",
            "size": 1234,
            "isSource": true
        },
        "source/usfm/MAT.sfm": {
            "checksum": {
                "md5": "0123456789abcdef0123456789abcdef"
            },
            "mimeType": "text/x-sfm",
            "scope": {
                "MAT": [
                    "1:3",
                    "1:5",
                    "1:7-11"
                ]
            },
            "size": 1234,
            "isSource": true
        },
        "release/text/USX_1/OTINT.usx": {
            "checksum": {
                "md5": "0123456789abcdef0123456789abcdef"
            },
            "mimeType": "text/x-usx+xml",
            "role": "intot",
            "size": 1234
        },
        "release/text/USX_1/GEN.usx": {
            "checksum": {
                "md5": "0123456789abcdef0123456789abcdef"
            },
            "mimeType": "text/x-usx+xml",
            "scope": {
                "GEN": []
            },
            "size": 1234
        },
        "release/text/USX_1/EXO.usx": {
            "checksum": {
                "md5": "0123456789abcdef0123456789abcdef"
            },
            "mimeType": "text/x-usx+xml",
            "scope": {
                "EXO": [
                    "1-12"
                ]
            },
            "size": 1234
        },
        "release/text/USX_1/LEV.usx": {
            "checksum": {
                "md5": "0123456789abcdef0123456789abcdef"
            },
            "mimeType": "text/x-usx+xml",
            "scope": {
                "LEV": [
                    "2:3-3:7"
                ]
            },
            "size": 1234
        },
        "release/text/USX_1/INTNT.usx": {
            "checksum": {
                "md5": "0123456789abcdef0123456789abcdef"
            },
            "mimeType": "text/x-usx+xml",
            "role": "intnt",
            "size": 1234
        },
        "release/text/USX_1/INTMAT.usx": {
            "checksum": {
                "md5": "0123456789abcdef0123456789abcdef"
            },
            "mimeType": "text/x-usx+xml",
            "role": "intMAT",
            "size": 1234
        },
        "release/text/USX_1/MAT.usx": {
            "checksum": {
                "md5": "0123456789abcdef0123456789abcdef"
            },
            "mimeType": "text/x-usx+xml",
            "scope": {
                "MAT": [
                    "1:3",
                    "1:5",
                    "1:7-11"
                ]
            },
            "size": 1234
        },
        "unknownAdditive.foo": {
            "mimeType": "application/octet-stream",
            "size": 99
        }
    },
    "names": {
        "book-gen": {
            "abbr": {
                "fr": "Gn"
            },
            "short": {
